apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

patchesStrategicMerge: #(1)
  - patches/strategic-patch.yaml

patches: #(2)
  - path: patches/deployment-patch.json
    target:
      kind: Deployment
      name: my-app-01-deployment