apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  label1: label1 value
commonAnnotations:
  annotation1: annotation1 value