apiVersion: v1
kind: Service
metadata:
  namespace: application
  name: test-service
spec:
  type: ClusterIP
  selector:
    app: my-app-01
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    name: http
  sessionAffinity: None

