apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-01-deployment
  namespace: application
spec:
  template:
    spec:
      containers:
        - name: my-app-01
          resources:
            limits:
              cpu: 500m
              memory: 1G
            requests:
              cpu: 350m
              memory: 500M

